const handler = (api) => {
	api.addUtilities({".font-A":{"fontFamily":"'brandon-grotesque', sans-serif","fontWeight":"bold","textTransform":"uppercase"},".font-A-normal":{"fontFamily":"'brandon-grotesque', sans-serif"},".font-B":{"fontFamily":"'fira-sans', sans-serif"},".flex-center":{"@apply flex items-center justify-center":true},".inline-size":{"containerType":"inline-size"},".container-size":{"containerType":"size"},".i-fluid-text":{"fontSize":"calc(19px + 0.390625vw)","lineHeight":"calc(31px + 0.48828125vw)"},".i-fluid-header":{"fontSize":"calc(29px + 0.390625vw)","lineHeight":"calc(35px + 0.48828125vw)"}});
		api.addBase({":root":{},"img":{"maxWidth":"initial"},"html":{"@apply size-full":true},"body":{"@apply size-full overflow-hidden font-B text-@14 text-black":true,"wordWrap":"break-word","overflowWrap":"break-word"}});
		api.addComponents({".i-interact":{"@apply hover:[&:not(:disabled)]:brightness-[115%]\n      active:[&:not(:disabled)]:translate-y-px\n      focus:[&:not(:focus-visible)]:outline-none":true},".i-page":{"@apply block size-full overflow-auto px-@10 pt-@10 pb-@20":true},".i-title":{"@apply text-@16 font-A text-center overflow-hidden":true},".i-content":{"@apply rounded-@5 bg-white p-@20":true},".i-user-decision":{"@apply min-h-@50 max-h-@100 p-@10 rounded-@5\n      bg-white shadow-inner shadow-@blue/40\n      outline outline-1 outline-@blue/10":true},".i-controls":{"@apply bg-@blue-light i-shadow p-@20":true},".i-input":{"@apply rounded-@5\n      bg-white\n      ring-1 ring-@blue\n      focus:outline-none":true},".i-invalid":{"@apply ring-1\n      ring-yellow-500":true},".i-shadow":{"--tw-shadow":"0 0 14px 1px rgba(0, 0, 0, 0.4)","--tw-shadow-colored":"0 0 24px 1px var(--tw-shadow-color)","boxShadow":"var(--tw-ring-offset-shadow, 0 0 #0000),\n      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)"},".i-loader":{"@apply relative":true},".i-loader::before":{"@apply absolute left-1/2 top-1/2":true,"transform":"translate(-50%, -50%)","content":"''","width":"3rem","height":"3rem","--border":"5px","border":"var(--border) solid #f4f4f4","borderTopColor":"rgb(122 122 122 / 70%)","borderRadius":"50%","zIndex":-1,"animation":"i-loader-rotation 0.8s linear infinite"},"@keyframes i-loader-rotation":{"0%":{"transform":"translate(-50%, -50%) rotate(0deg)"},"100%":{"transform":"translate(-50%, -50%) rotate(360deg)"}}});
		api.addComponents({".i-btn":{"@apply i-interact h-@50\n      overflow-hidden rounded-@5\n      px-@10\n      py-@5 text-center\n      font-A text-@14 text-white\n      disabled:bg-@gray disabled:text-white":true},".i-btn-blue":{"@apply bg-@blue":true},".i-btn-red":{"@apply bg-@red":true},".i-btn-green":{"@apply bg-@green":true},".i-btn-white":{"@apply bg-white text-@blue border border-@blue":true},".i-btn-sharp":{"@apply rounded-none":true},".i-btn-select[selected=true]":{"@apply i-btn-green":true},".i-btn-select":{"@apply active:[&:not(:disabled)]:translate-y-0":true}});
};

const config = {};

export default {
	handler,
	config,
};